application: party-box
version: 1
runtime: python
api_version: 1

handlers:
- url: /rpc/.*
  script: rpc.py
- url: /jukebox/.*
  script: jukebox.py
  login: required
- url: /youtube/.*
  script: youtube/playlist.py
  login: required
