application: party-box
version: 1
runtime: python
api_version: 1

handlers:
- url: /youtube.*
  script: youtube.py
  login: required
- url: /admin/.*
  script: admin.py
  login: admin
- url: /static
  static_dir: static
