application: party-box
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: /
  static_files: static/home.html
  upload: static/home.html

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: youtube.py
  login: required
